name: Hello World!
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v4
      - name: show files
        run: ls -la
      - name: Show Readme file
        run: cat README.md
      - name: Hello World!
        run: echo "Hello World"
      - name: Test Environment Variable
        env:
          MESSAGE: "Hello this is a environment variable "
        run: |
          echo $MESSAGE
          echo ${{ secrets.TEST_PASSWORD }}
